version: '3'
services:
  bot:
    image: ghcr.io/yoyolick/mitsuri:main
    ports:
      - 3003:3000
    volumes:
      - type: bind
        source: /home/dietpi/projects/mitsuri
        target: /usr/mitsuri
    restart: unless-stopped