name: cleanup

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Delete old package versions
        uses: smartsquaregmbh/delete-old-packages@v0.6.0
        with:
          names: ${{ env.PACKAGE_ID }}