name: nightly build

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v3
        with:
          package-name: mitsuri.nightly
          min-versions-to-keep: 0
      - name: Delete old package versions
        uses: actions/delete-package-versions@v3
        with:
          package-name: mitsuri.main
          min-versions-to-keep: 0
      - name: Delete old package versions
        uses: actions/delete-package-versions@v3
        with:
          package-name: mitsuri:main
          min-versions-to-keep: 0
      - name: Delete old package versions
        uses: actions/delete-package-versions@v3
        with:
          package-name: mitsuri
          min-versions-to-keep: 0